language: minimal
dist: xenial
addons:
  apt:
    sources:
      - docker-xenial

env:
  ADD_TAG=""

before_install:
# Login to hub.docker.com
- echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin

install:
# Add docker-retag executable
- wget -q https://github.com/joshdk/docker-retag/releases/download/0.0.2/docker-retag && chmod +x docker-retag

script:
# Build Image via kaniko
- docker run
    -v "$TRAVIS_BUILD_DIR":/workspace
    -v $HOME/.docker:/kaniko/.docker
  gcr.io/kaniko-project/executor:latest
    --context=/workspace
    --build-arg VCS_REF=$TRAVIS_COMMIT
    --build-arg GIT_REPO=https://github.com/$TRAVIS_REPO_SLUG
    --build-arg BUILD_DATE=$(date -u +"%Y-%m-%d")
    --verbosity=info
    --destination=dcso/tiffy

# Retag images for other tags
- for i in $ADD_TAG;
  do
    ./docker-retag dcso/tiffy $i;
  done

# # don't notify me when things fail
# notifications:
#   email: false
