TIE:
  apiurl: "https://foo.bar/api/"
  apikey: "12345683127481209123789"

MISP:
  events:
    base_threat_level: 3
    published: False
  org:
    name: "ACME"
    uuid: "5804adw2-12fe-1234-34av-07lk82aw012a"
  attributes:
    to_ids: False
    to_ids_threshold: 90

  